export const BEHAVIOUR_CATEGORY_OPTIONS = [
  { value: 'Respect', label: 'Respect' },
  { value: 'Responsibility', label: 'Responsibility' },
  { value: 'Resilience', label: 'Resilience' },
  { value: 'Kindness', label: 'Kindness' },
  { value: 'Cooperation', label: 'Cooperation' },
  { value: 'Leadership', label: 'Leadership' },
  { value: 'Positive Attitude', label: 'Positive Attitude' },
  { value: 'Community Contribution', label: 'Community Contribution' },
  { value: 'Disruption', label: 'Disruption' },
  { value: 'Defiance / Non-Compliance', label: 'Defiance / Non-Compliance' },
  { value: 'Disrespect', label: 'Disrespect' },
  { value: 'Inappropriate Language', label: 'Inappropriate Language' },
  { value: 'Bullying', label: 'Bullying' },
  { value: 'Discriminatory Behaviour', label: 'Discriminatory Behaviour' },
  { value: 'Dishonesty', label: 'Dishonesty' },
  { value: 'Vandalism / Damage to Property', label: 'Vandalism / Damage to Property' },
  { value: 'Physical Aggression', label: 'Physical Aggression' },
  { value: 'Non-Physical Aggression', label: 'Non-Physical Aggression' },
  { value: 'Inappropriate Use of Technology', label: 'Inappropriate Use of Technology' },
  { value: 'Truancy / Lateness', label: 'Truancy / Lateness' },
  { value: 'Poor Preparedness', label: 'Poor Preparedness' },
  { value: 'Substance Use / Possession', label: 'Substance Use / Possession' },
  { value: 'Sexual Misconduct / Harassment', label: 'Sexual Misconduct / Harassment' },
];
